#!/bin/sh
export TARGET=arm-apple-darwin11
export CC=ios-clang
export PREFIX=/opt/iPhoneOS8.1.sdk
export CFLAGS="$CFLAGS -g0 -O2"
./configure --host=$TARGET --prefix=$PREFIX --libdir=$PREFIX/usr/lib --includedir=$PREFIX/usr/include
