#!/bin/sh
export TOOLCHAIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
export TARGET=armv7a-linux-androideabi
export API=16
export CC=$TOOLCHAIN/bin/$TARGET$API-clang
export TARGET=arm-linux-androideabi
export PREFIX=$TOOLCHAIN/sysroot/usr
export CPPFLAGS="$CPPFLAGS -DDEBUG"
export CFLAGS="$CFLAGS -g"
./configure --host=$TARGET --prefix=$PREFIX --libdir=$PREFIX/lib/$TARGET/$API --disable-static
